name: Build turboinstaller

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.11]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0

    - name: Setup Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Linux ELF
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --onefile turboinstall.py --icon=resources/icon.png

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: turboinstaller-${{ matrix.os }}
        path: dist/